export default {
    robots: [
        {
            name: 'Massacre',
            image: 'https://www.clementoni.com/media/prod/es/15285/crea-tu-robot_hmzWnwU.jpg',
            speed: 3,
            stamina: 1,
            date: '02/04/2018',
        },
        {
            id: 2,
            title: 'Neuromante',
            year: '1984',
            authors: [{ fullName: 'William Gibson', id: 0 }],
            txtAuthors: 'William Gibson',
            spanishEdition: {
                place: 'Barcelona',
                publisher: 'Minotauro',
                year: '1989',
                ISBN: '84-450-7084-3',
            },
            genre: 'Novela',
            notice: 'Un futuro invadido por microprocesadores, en el que la información es la materia prima. Vaqueros como Henry Dorrett Case se ganan la vida hurtando información, traspasando defensas electrónicas, bloques tangibles y luminosos, como rascacielos geométricos. En este espeluznante y sombrío futuro la mayor parte del este de Norteamérica es una única y gigantesca ciudad, casi toda Europa un vertedero atómico y Japón una jungla de neón, corruptora y brillante, donde una persona es la suma de sus vicios.',
            coverImage: 'Neuromante.jpg',
        },
        {
            id: 3,
            title: 'Hardwired',
            year: '1986',
            authors: [{ fullName: 'Walter Jon Williams', id: 3 }],
            txtAuthors: 'Walter Jon Williams',
            spanishEdition: {
                place: 'Barcelona',
                publisher: 'Martinez Roca',
                year: '1995',
            },
            genre: 'Novela',
            notice: 'La Tierra está dominada por compañías; su economía y los mercados dependen de decisiones tomadas en asépticos despachos orbitales. Los antiguos gobiernos terrestres desaparecieron en medio de un conflicto bélico que desintegró por completo sus esferas de influencia. La población terrestre depende de la tecnología orbital en su lucha por la supervivencia, y en los núcleos urbanos impera la ley del más fuerte. En medio de la anarquía reinante, dos personajes singulares luchan día a día por mantener su independencia. El Cowboy, un tanquista que se gana la vida como contrabandista a los mandos de un vehículo cibernético blindado, y Sarah, una buscona que trabaja como guardaespaldas o prostituta y que sueña con poder abandonar el pozo gravitatorio.',
            coverImage: 'HardWired.jpg',
        },
        {
            id: 4,
            title: 'Cuando la gravedad falla',
            year: '1987',
            authors: [{ fullName: 'George Alec Effinger', id: 6 }],
            txtAuthors: 'George Alec Effinger',
            spanishEdition: {
                place: 'Barcelona',
                publisher: 'Martinez Roca',
                year: '1989',
            },
            genre: 'Novela',
            notice: 'El Budayén, los bajos fondos de una ciudad árabe anónima, está construido al lado del cementerio, y quien se interna en sus callejones lo hace consciente del peligro que corre: ni sus habitantes -prostitutas, proxenetas y traficantes de drogas- ni la policía se preocupan demasiado si un desconocido aparece acuchillado y tirado en la esquina. Tal es el ambiente en el que se ha criado Marîd Audran, un hombretón que nunca ha necesitado llevar armas y que es respetado en su independencia. Pero nadie podría haber imaginado la pesadilla en la que se convertiría su vida después de que un extraño muriera asesinado por alguien conectado a un módulo de James Bond... Una novela vertiginosa, en la que se dan cita los logros de la informática, la novela negra y la ciencia ficción.',
            coverImage: 'Cuando_falla_la_gravedad.jpg',
        },
        {
            id: 5,
            title: 'Islas en la red',
            year: '1988',
            authors: [{ fullName: 'Bruce Sterling', id: 2 }],
            txtAuthors: 'Bruce Sterling',
            spanishEdition: {
                place: 'Barcelona',
                publisher: 'Destino (Colección Cronos; 11)',
                year: '1990',
                ISBN: '84-233-1898-2',
            },
            genre: 'Novela',
            notice: 'Novela ganadora del premio John W. Campbell Memorial de 1989. Laura y David Websters son dos yuppies del siglo XXI, cuyas ansias de progresar están tamizadas por su lealtad a la empresa a la que pertenecen, Rizome, que como todos los grandes imperios comerciales que dominan el mundo, se ha convertido en un benévolo patriarcado a la japonesa, familiar y protector hacia sus empleados. El término de la guerra fría y la abolición de los arsenales nucleares ha alejado definitivamente de la Tierra la amenaza apocalíptica de un holocausto global; pero la omnipresencia de la informática y la instantaneidad de las comunicaciones a través de la Red global han visto la eclosión de otro fenómeno: los piratas de datos, instalados en paraísos como la isla de Granada o Singapur, que dominan por completo el mundo de la información.',
            coverImage: 'Islas_en_la_red.jpg',
        },
        {
            id: 6,
            title: 'La máquina diferencial',
            year: '1991',
            authors: [
                { fullName: 'Bruce Sterling', id: 2 },
                { fullName: 'William Gibson', id: 1 },
            ],
            txtAuthors: 'Bruce Sterling & William Gibson',
            spanishEdition: {
                place: 'Arganda del Rey',
                publisher: 'La Factoría de Ideas',
                year: '2006',
                ISBN: '8498002818',
            },
            genre: 'Novela',
            notice: 'Ucronía en la época victoriana en donde el Partido Industrial Radical, liderado por un longevo Lord Byron (que sobrevivió a la guerra de independencia griega, a diferencia de lo que ocurrió en la realidad) obtiene el poder, y el matemático Charles Babbage construye exitosamente su proyectada máquina diferencial',
            coverImage: 'La_maquina_diferencial.jpg',
        },
        {
            id: 7,
            title: 'Snow Crash',
            year: '1992',
            authors: [{ fullName: 'Neal Stephenson', id: 8 }],
            txtAuthors: 'Neal Stephenson',
            spanishEdition: {
                place: 'Barcelona',
                publisher: 'Gigamesh',
                year: '2000',
            },
            genre: 'Novela',
            notice: 'La novela que revitalizó el ciberpunk... con unas gotas de sentido del humor. A ambos lados de la autopista de Los Ángeles, las franquicias se suceden unas a otras hasta donde alcanza la vista: las Puertas Perladas del Reverendo Wayne, el Nuevo y Más Grande Hong Kong de Mr. Lee, Pizzas Cosa Nostra, Inc. de Tío Enzo... El único respiro que hay en el mar de logos y carteles se encuentra al otro lado de las bien guardadas fronteras de las ciudades estado independientes, cuyos ciudadanos intentan no abandonar nunca. ¿A quién podría extrañar que casi todo el mundo opte por buscar refugio en un universo virtual? El Metaverso es el último reducto de la libertad, el único lugar donde todo sigue siendo posible sin jugarse la piel. Pero ahora está siendo amenazado por un nuevo tipo de virus conocido como Snow Crash, un virus que amenaza con desencadenar el infocalipsis... Snow Crash es una de esas raras novelas que marca un relevo generacional: sus páginas destilan la presencia de una voz innovadora que contempla el mundo con ironía desde una perspectiva tan fresca como radical. Es una obra pirotécnica y vertiginosa, guiada por una incontenible pasión de narrar, pletórica de ideas nuevas y que destila un tono cómplice y socarrón en sus todas sus páginas. Una revolución de un solo libro en la historia reciente del género.',
            coverImage: 'Snow_Crash.jpg',
        },
        {
            id: 8,
            title: 'Carbono Alterado',
            year: '2002',
            authors: [{ fullName: 'Richard Morgan', id: 4 }],
            txtAuthors: 'Richard Morgan',
            spanishEdition: {
                place: 'Barcelona',
                publisher: 'Minotauro',
                year: '2005',
            },
            genre: 'Novela',
            notice: 'En el siglo XXV, la humanidad se ha expandido por la galaxia supervisada por la fuerza de Enviados de la ONU, que vigila y ejerce el control en los conflictos. Mientras las divisiones de clase, raza y religión persisten, los avances tecnológicos ha redefinido la vida. En este momento, la conciencia se almacena en un disco digital implantado en la base del cerebro, y resulta fácilmente descargable en un nuevo cuerpo, como si de un molde se tratara, haciendo que la muerte parezca tansólo un disparo contra la pantalla. En una sociedad en la que morir se ha convertido en algo obsoleto, el suicidio y el asesinato adquieren significados totalmente distintos. Después de una misión como Enviado de la ONU, Takeshi Kovacs vuelve a la Tierra descargado en el cuerpo de un investigador contratado por Laurens Bancroft, uno de los hombres más ricos de Bay City (San Francisco). Bancroft asegura que ha sido asesinado, pero la versión de la policía es que se ha suicidado. A medida que investiga, Takeshi va destapando una trama de conspiración y prostitución que lo lleva a enfrentarse con un personaje con un pasado de lo más desagradable. Carbono alterado es una sólida novela cosida con intriga, un ritmo trepidante, sexo, drogas y violencia, que ha cosechado gran éxito de público y crítica en el Reino Unido y Estados Unidos.',
            coverImage: 'Carbono_Alterado.jpg',
        },
        {
            id: 9,
            title: 'Ciberpunk. Más allá de Matrix',
            year: '2003',
            authors: [{ fullName: 'Horacio Moreno', id: 5 }],
            txtAuthors: 'Horacio Moreno',
            spanishEdition: {
                place: 'Sant Andreu de la Barca',
                publisher: 'Círculo Latino',
                year: '2003',
                ISBN: '9788496129078',
            },
            genre: 'Essay',
            notice: 'Ensayo ilustrado acerca de este subgenero de la Ciencia Ficción.',
            coverImage: 'Cyberpunk.jpg',
        },
    ],
};
